name: 5-include-with-deploy-template--build

on:
  pull_request:
    branches: main # Run workflow on PRs to the main branch.

  # Run workflow on pushes to any branch, except the main branch.
  push:
    branches-ignore: main

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

  # ðŸ‘‡ Allows this workflow to be called from the deployment workflow, and provide default values when not.
  workflow_call:
    inputs:
      artifactName:
        description: The name of the artifact to upload to.
        required: false
        type: string
        default: buildArtifact # Provide a default value for when the workflow is not called from the deployment workflow.

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo source code
        uses: actions/checkout@v3

      # Steps to version, build, and test the code go here.

      # Call a simple PowerShell script in this example to easily pass/fail the build for testing.
      - shell: pwsh
        run: ./src/pass-or-fail-build.ps1

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifactName }}
          path: ./ # Put the path to the build artifact files directory here.
